---
- name: Set up desktop environment
  hosts: local
  roles:
    - role: base
    - role: xorg
    - role: gnome
    - role: argos
    - role: dconf

- name: Set up development environment
  hosts: local
  roles:
    - role: ssh
    - role: git
    - role: yay
    - role: packages
    - role: terminator
    - role: zsh
    - role: rofi
    - role: docker
    - role: ruby
    - role: node
    - role: tailscale
