---
- name: pacman | update cache
  become: true
  become_user: root
  community.general.pacman:
    update_cache: true

- name: pacman | install tools
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ official_packages }}"

- name: flatpak | install flatpak packages
  community.general.flatpak:
    name: "{{item}}"
    method: system
    state: present
  with_items: "{{ flatpak_packages }}"

- name: Register yay installation status
  ansible.builtin.command: which yay
  changed_when: false
  failed_when: false
  register: yay_installed

- name: Create the `aur_builder` user
  become: true
  become_user: root
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"

- name: git | clone yay
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/tmp/yay-bin"
  when: yay_installed.rc not in [0]

- name: Install yay-bin using makepkg and a local PKGBUILD.
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay-bin
    use: makepkg
    local_pkgbuild: /tmp/yay-bin
    state: present
  when: yay_installed.rc not in [0]

- name: yay | install tools
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  with_items: "{{ aur_packages }}"

- name: Make sure service has time to start or stop
  pause:
    seconds: 15
  when: not ansible_check_mode

- name: Delete the `aur_builder` user
  become: true
  become_user: root
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true

- name: Remove aur_builder sudoer file
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent
