- name: file | link config file
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory
    mode: 0644

- name: command | fetch github.com RSA key
  ansible.builtin.command: ssh-keyscan -t rsa github.com
  register: github_rsa_key
  changed_when: false

- name: known_hosts | Add github.com RSA key
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ github_rsa_key.stdout }}"
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    state: present
