- name: file | link config file
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory

- name: Fetch github.com RSA key
  command: ssh-keyscan -t rsa github.com
  register: github_rsa_key
  changed_when: false

- name: Add github.com RSA key
  known_hosts:
    name: github.com
    key: "{{ github_rsa_key.stdout }}"
    path: "{{ dotfiles_user_home }}/.ssh/known_hosts"
    state: present
