---
- name: pacman | install tailscale
  become: true
  become_user: root
  community.general.pacman:
    name: tailscale
    state: present

- name: systemd | run tailscale
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
