---
- name: pacman | install gnome and tools
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell
    - gnome-control-center
    - gnome-keyring
    - gnome-tweak-tool
    - nautilus
    - xdg-user-dirs
    - networkmanager
    - gdm

- name: jaredhocutt.gnome_extensions | gnome config
  include_role:
    name: jaredhocutt.gnome_extensions
  vars:
    gnome_extension_ids:
      - 1160  # dash-to-panel@jderose9.github.com
      - 1010  # arch-update@RaphaelRochet
      - 615   # appindicatorsupport@rgcjonas.gmail.com
      - 858   # shell-volume-mixer@derhofbauer.at
      - 19    # user-theme@gnome-shell-extensions.gcampax.github.com
      - 1007  # windowIsReady_Remover@nunofarruca@gmail.com
      - 1040  # randomwallpaper@iflow.space
      - 2741  # remove-alt-tab-delay@daase.net
      - 750   # openweather-extension@jenslody.de

- name: lineinfile | disable wayland for gdm
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    search_string: "#WaylandEnable=false"
    line: WaylandEnable=false

- name: lineinfile | set xorg as default
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    insertafter: "WaylandEnable=false"
    line: DefaultSession=gnome-xorg.desktop

- name: systemd | run gdm
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: gdm
    enabled: true

- name: systemd | run NetworkManager
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true

- name: systemd | run bluetooth
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true

- name: file | creates .themes directory
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.themes"
    state: directory

- name: stat | .themes/Nordic
  stat:
    path: "{{ dotfiles_user_home }}/.themes/Nordic"
  register: nordic_stat

- name: unarchive | Nordic theme
  ansible.builtin.unarchive:
    src: https://github.com/EliverLara/Nordic/archive/refs/heads/master.zip
    dest: "{{ dotfiles_user_home }}/.themes"
    remote_src: true
  when: not nordic_stat.stat.exists

- name: command | rename Nordic folder
  ansible.builtin.command: "mv {{ dotfiles_user_home }}/.themes/Nordic-master {{ dotfiles_user_home }}/.themes/Nordic"
  args:
    creates: "{{ dotfiles_user_home }}/.themes/Nordic"
  when: not nordic_stat.stat.exists

- name: stat | .local/share/icons/Tela
  stat:
    path: "{{ dotfiles_user_home }}/.local/share/icons/Tela"
  register: tela_stat

- name: unarchive | Tela icons
  ansible.builtin.unarchive:
    src: https://github.com/vinceliuice/Tela-icon-theme/archive/refs/heads/master.zip
    dest: /tmp
    remote_src: true
  when: not tela_stat.stat.exists

- name: command | install Tela icons
  ansible.builtin.command: "sh /tmp/Tela-icon-theme-master/install.sh"
  args:
    creates: "{{ dotfiles_user_home }}/.local/share/icons/Tela"
  when: not tela_stat.stat.exists
