---
- name: pacman | install gnome and tools
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell
    - gnome-control-center
    - gnome-keyring
    - gnome-tweak-tool
    - gnome-disk-utility
    - gnome-shell-extension-appindicator
    - nautilus
    - xdg-user-dirs
    - networkmanager
    - gdm

- name: petermosmans.customize-gnome | gnome extensions
  tags:
    - gnome
  include_role:
    name: petermosmans.customize-gnome
  vars:
    gnome_extensions:
      - name: arch-update@RaphaelRochet
      - name: dash-to-panel@jderose9.github.com
      - name: shell-volume-mixer@derhofbauer.at
      - name: windowIsReady_Remover@nunofarruca@gmail.com
      - name: appindicatorsupport@rgcjonas.gmail.com
      - name: argos@pew.worldwidemann.com
      - name: randomwallpaper@iflow.space
      - name: remove-alt-tab-delay@daase.net
      - name: tailscale-status@maxgallup.github.com
      - name: openweather-extension@jenslody.de
      - name: IP-Finder@linxgem33.com
      - name: user-theme@gnome-shell-extensions.gcampax.github.com
      - name: yomun@yahoo.com
      - name: sound-output-device-chooser@kgshank.net
      - name: visualizer@sound.org
      - name: BingWallpaper@ineffable-gmail.com
      - name: nightthemeswitcher@romainvigier.fr

- name: lineinfile | disable wayland for gdm
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    search_string: "#WaylandEnable=false"
    line: WaylandEnable=false

- name: lineinfile | set xorg as default
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    insertafter: "WaylandEnable=false"
    line: DefaultSession=gnome-xorg.desktop

- name: systemd | run gdm
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: gdm
    enabled: true

- name: systemd | run NetworkManager
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true

- name: systemd | run bluetooth
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
