---
- name: pacman | update cache
  become: true
  become_user: root
  community.general.pacman:
    update_cache: true

- name: pacman | install tools
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ official_packages }}"
