- name: pacman | install terminator
  become: yes
  become_user: root
  community.general.pacman:
    name: terminator
    state: present

- name: file | link config file
  ansible.builtin.file:
    path: "{{ dotfiles_user_home }}/.config/terminator"
    state: directory

- name: file | link config file
  ansible.builtin.file:
    src: "{{ dotfiles_home }}/roles/terminator/files/config.link"
    dest: "{{ dotfiles_user_home }}/.config/terminator/config"
    state: link
    force: yes
    follow: false
