---
- name: pacman | install rofi
  become: true
  become_user: root
  community.general.pacman:
    name: rofi
    state: present

- name: file | link rofi config file
  file:
    src: "{{ dotfiles_home }}/roles/rofi/files/config.rasi.link"
    dest: "{{ dotfiles_user_home }}/.config/rofi/config.rasi"
    state: link
    force: true

- name: file | link rofi theme file
  file:
    src: "{{ dotfiles_home }}/roles/rofi/files/theme.rasi.link"
    dest: "{{ dotfiles_user_home }}/.config/rofi/theme.rasi"
    state: link
    force: true
