---
- name: get_url | download nvm installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
    dest: /tmp/nvm-installer.sh

- name: file | change permissions
  file:
    dest: /tmp/nvm-installer.sh
    mode: a+x

- name: command | execute nvm installer
  command: /tmp/nvm-installer.sh
  args:
    creates: "{{ dotfiles_user_home }}/.nvm"

- name: nvm | install node
  shell: "source {{ dotfiles_user_home }}/.nvm/nvm.sh && nvm install {{ item }}"
  args:
    creates: "{{ dotfiles_user_home }}/.nvm/versions/node/{{ item }}"
  with_items: "{{ node.versions }}"

- name: nvm | set node default
  shell: "source {{ dotfiles_user_home }}/.nvm/nvm.sh && nvm alias default {{ node.default_version }}"
  args:
    creates: "{{ dotfiles_user_home }}/.nvm/alias/default"

- name: npm | install yarn
  shell: "source {{ dotfiles_user_home }}/.nvm/nvm.sh && npm install --global yarn"
  args:
    creates: "{{ dotfiles_user_home }}/.nvm/versions/node/{{ node.default_version }}/lib/node_modules/yarn"
