- name: Run the equivalent of "pacman -Syu" as a separate step
  become: yes
  become_user: root
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: pacman | install base packages
  become: yes
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"
