- name: gpg | check for rvm_1
  shell: "gpg --list-keys | grep -w {{ gpg_keys.rvm_1 }}"
  register: rvm_1_exist
  changed_when: false
  failed_when: rvm_1_exist.rc not in [ 0, 1 ]

- name: gpg | check for rvm_2
  shell: "gpg --list-keys | grep -w {{ gpg_keys.rvm_2 }}"
  register: rvm_2_exist
  changed_when: false
  failed_when: rvm_2_exist.rc not in [ 0, 1 ]

- name: gpg | recv-key rvm_1 from rvm
  command: "gpg2 --recv-keys {{ gpg_keys.rvm_1 }}"
  when: rvm_1_exist.rc == 1

- name: gpg | recv-key rvm_2 from rvm
  command: "gpg2 --recv-keys {{ gpg_keys.rvm_2 }}"
  when: rvm_2_exist.rc == 1

- name: shell | curl rvm installer
  shell: curl -sSL https://get.rvm.io | bash -s stable
  args:
    creates: "{{ dotfiles_user_home }}/.rvm"

- name: rvm | install ruby
  command: "{{ dotfiles_user_home }}/.rvm/bin/rvm install {{ item }}"
  args:
    creates: "{{ dotfiles_user_home }}/.rvm/gems/ruby-{{ item }}"
  with_items: "{{ ruby.versions }}"

- name: rvm | set ruby default
  command: "{{ dotfiles_user_home }}/.rvm/bin/rvm alias create default ruby-{{ ruby.default_version }}"
  args:
    creates: "{{ dotfiles_user_home }}/.rvm/config/alias"

- name: file | link .gemrc file
  file:
    src: "{{ dotfiles_home }}/roles/ruby/files/gemrc.link"
    dest: "{{ dotfiles_user_home }}/.gemrc"
    state: link
    force: yes
